"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "./footer";
import ContactModal from "./components/ContactModal";
import { ContactModalProvider, useContactModal } from "./ContactModalContext";
import { LanguageProvider } from "./LanguageContext";
import { Analytics } from "@vercel/analytics/next";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function RootLayoutContent({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isContactModalOpen, setIsContactModalOpen } = useContactModal();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar onContactClick={() => setIsContactModalOpen(true)} />
        {children}
        <ContactModal open={isContactModalOpen} onClose={() => setIsContactModalOpen(false)} />
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LanguageProvider>
      <ContactModalProvider>
        <RootLayoutContent>{children}</RootLayoutContent>
      </ContactModalProvider>
    </LanguageProvider>
  );
}
